### PR TITLE
test: initial playwright e2e tests OH-52

### PR DESCRIPTION
**Pull request by terovirtanen**
### Closes :no_good_woman:

**[OH-52](https://helsinkisolutionoffice.atlassian.net/browse/OH-52)**

## Additional notes :spiral_notepad:

[OH-52]: https://helsinkisolutionoffice.atlassian.net/browse/OH-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr138-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr138-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr138-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by jorilindell — COMMENTED** [review]
`/report` could be added to `.gitignore` and the `/report` folder could be removed. I think they shouldn't be in the repo.

**Comment by terovirtanen** [comment]
> `/report` could be added to `.gitignore` and the `/report` folder could be removed. I think they shouldn't be in the repo.

Yep, report -folder should not be in the repo. Now removed.

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr138-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by jorilindell — APPROVED** [review]
Very good!

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr138-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
