### PR TITLE
LINK-2075 | add lang attribute to Talpa url

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Add lang attribute to Talpa url
Also clear data from session storage before moving to Talpa

## Closes
[LINK-2075](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2075)

[LINK-2075]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr158-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr158-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr158-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by jorilindell** [comment]
There is a PR on BE side to return lang parameter in checkout url so this PR is mostly unnecessary. I'll create an other PR to clear session storage before moving to Talpa.

Link to the BE PR: https://github.com/City-of-Helsinki/linkedevents/pull/929

**Pull request closed without merging**
