### PR TITLE
fix: normalize font sizes LINK-2149

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description :sparkles:
- Normalize font-sizes to help with scaling when users changes font-size on device
- Set meta viewport

### Closes :no_good_woman:

**[LINK-2149](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2149):**

## Additional notes :spiral_notepad:

[LINK-2149]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr187-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr187-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr187-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr187-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr187-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr187-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
