### PR TITLE
fix: singleSelect remove deprecated selection status LINK-2153

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description :sparkles:
Select components get A11Y message props are deprecated, seems to work correctly without them.

### Closes :no_good_woman:

**[LINK-2153](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2153):**

## Additional notes :spiral_notepad:

[LINK-2153]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr189-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr189-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr189-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr189-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr189-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr189-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
