### PR TITLE
feat: add all sub events to the ics file

### PR DESCRIPTION
**Pull request by jorilindell**
## Description 
Add all sub-events to an ics file if super event type of the event is recurring event

## Closes
[LINK-2003](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2003)

[LINK-2003]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr154-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr154-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr154-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr154-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr154-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
