### PR TITLE
fix: a11y heading levels LINK-2150 LINK-2157

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description :sparkles:

Fixing signup form heading levels.

### Closes :no_good_woman:

**[LINK-2150](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2150)**
**[LINK-2157](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2157)**

## Additional notes :spiral_notepad:

[LINK-2150]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-2157]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr188-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr188-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDREGISTRATIONS-UI branch is deployed to platta: https://linkedregistrations-pr188-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedregistrations-pr188-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
