### PR TITLE
LINK-1484 | 3/5 Move delete signup button to the page bottom

### PR DESCRIPTION
**Pull request by jorilindell**
## Description :sparkles:
Replace LoadingButton component with HDS Button

This is one of the 5 PRs that replaced https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/74. The purpose of these PRs is to implement pages to update signups and signup groups

PR Parts:
- Replace LoadingButton component with HDS Button (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/81)
- Move signup form test util functions to separate file (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/82)
- **Move delete signup button to the page bottom**
- Util functions and queries to update signups and signups groups (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/84)
- Changes in UI components to support updating signup or signup group (https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/85)

## Partially closes
[LINK-1484](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1484)

[LINK-1484]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by timwessman** [comment]
Code looks good and works great! I'm not if it is part of this, but the number in `ParticipantAmountSelector` doesn't update if participant is removed from the remove participant -button.

**Comment by timwessman** [comment]
Outline of remove participant button doesn't show on keyboard focus 
Screenshot 2023-10-03 at 16 36 10

**Comment by jorilindell** [comment]
> Code looks good and works great! I'm not if it is part of this, but the number in `ParticipantAmountSelector` doesn't update if participant is removed from the remove participant -button.

It was kind of intentional decision to leave it that way. The reason was that number of signups is updated only after explicitly click update button, so it felt kind of wrong to update the same value after deleting a signup. But maybe it could be fixed. I added a separate JIRA ticket for it and created separate PR as well. I fixed it to the Linked Components UI at the same time.

Links to PRs:
https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/87
https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/245

JIRA ticket:
https://helsinkisolutionoffice.atlassian.net/browse/LINK-1619

**Comment by jorilindell** [comment]
> Outline of remove participant button doesn't show on keyboard focus Screenshot 2023-10-03 at 16 36 10

Fixed to https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/85 PR by commit https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/85/commits/8b85da556756d9bc2bc500f5dd14cace9f2b1416. Styles were overridden by some Firefox default `:focus-visible` styles. Also fixed the button background color to match accordion background color

**Review by timwessman — APPROVED** [review]

**Pull request merged**
